#include "M3lody_Const.h"
/*
none
note(value)
program_change(value)
control_change(index)
pitch_bend(value)
after_touch(value)
song_position(value)
song_select(value)
rt_clock()
rt_start()
rt_stop()
rt_tick()
rt_continue()
custom_action(value)
*/




uint16_t keyconfig[] = {  
// PS2_KEY_NUM         0x01
  none,
// PS2_KEY_SCROLL      0x02
  none,
// PS2_KEY_CAPS        0x03
  none,
// PS2_KEY_PRTSCR      0x04
  none,
// PS2_KEY_PAUSE       0x05
  none,
// PS2_KEY_L_SHIFT     0x06
  none,
// PS2_KEY_R_SHIFT     0x07
  none,
// PS2_KEY_L_CTRL      0X08
  none,
// PS2_KEY_R_CTRL      0X09
  none,
// PS2_KEY_L_ALT       0x0A
  none,
// PS2_KEY_R_ALT       0x0B
  none,
/* Sometimes called windows key */
// PS2_KEY_L_GUI       0x0C
  none,
// PS2_KEY_R_GUI       0x0D
  none,
// PS2_KEY_MENU        0x0E
  none,
/* Break is CTRL + PAUSE generated inside keyboard */
// PS2_KEY_BREAK       0x0F
  none,
/* Generated by some keyboards by ALT and PRTSCR */
// PS2_KEY_SYSRQ       0x10
  none,
// PS2_KEY_HOME        0x11
  none,
// PS2_KEY_END         0x12
  none,
// PS2_KEY_PGUP        0x13
  none,
// PS2_KEY_PGDN        0x14
  none,
// PS2_KEY_L_ARROW     0x15
  none,
// PS2_KEY_R_ARROW     0x16
  none,
// PS2_KEY_UP_ARROW    0x17
  custom_action(1),
// PS2_KEY_DN_ARROW    0x18
  custom_action(2),
// PS2_KEY_INSERT      0x19
  none,
// PS2_KEY_DELETE      0x1A
  none,
// PS2_KEY_ESC         0x1B
  none,
// PS2_KEY_BS          0x1C
  none,
// PS2_KEY_TAB         0x1D
  none,
// PS2_KEY_ENTER       0x1E
  none,
// PS2_KEY_SPACE       0x1F
  none,
// PS2_KEY_KP0         0x20
  none,
// PS2_KEY_KP1         0x21
  none,
// PS2_KEY_KP2         0x22
  none,
// PS2_KEY_KP3         0x23
  none,
// PS2_KEY_KP4         0x24
  none,
// PS2_KEY_KP5         0x25
  none,
// PS2_KEY_KP6         0x26
  none,
// PS2_KEY_KP7         0x27
  none,
// PS2_KEY_KP8         0x28
  none,
// PS2_KEY_KP9         0x29
  none,
// PS2_KEY_KP_DOT      0x2A
  none,
// PS2_KEY_KP_ENTER    0x2B
  none,
// PS2_KEY_KP_PLUS     0x2C
  none,
// PS2_KEY_KP_MINUS    0x2D
  none,
// PS2_KEY_KP_TIMES    0x2E
  none,
// PS2_KEY_KP_DIV      0x2F
  none,
// PS2_KEY_0           0X30
  note(D3),
// PS2_KEY_1           0X31
  none,
// PS2_KEY_2           0X32
  note(C2),
// PS2_KEY_3           0X33
  note(D2),
// PS2_KEY_4           0X34
  none,
// PS2_KEY_5           0X35
  note(F2),
// PS2_KEY_6           0X36
  note(G2),
// PS2_KEY_7           0X37
  note(A2),
// PS2_KEY_8           0X38
  none,
// PS2_KEY_9           0X39
  note(C3),
// PS2_KEY_APOS        0X3A
  none,
// PS2_KEY_COMMA       0X3B
  note(c2),
// PS2_KEY_MINUS       0X3C
  none,
// PS2_KEY_DOT         0X3D
  note(d2),
// PS2_KEY_DIV         0X3E
  none,
/* Some Numeric keyboards have an '=' on right keypad */
// PS2_KEY_KP_EQUAL    0x3F
  none,
/* Single quote or back quote */
// PS2_KEY_SINGLE      0X40
  none,
// PS2_KEY_A           0X41
  none,
// PS2_KEY_B           0X42
  note(g1),
// PS2_KEY_C           0X43
  note(e1),
// PS2_KEY_D           0X44
  note(D1),
// PS2_KEY_E           0X45
  note(e2),
// PS2_KEY_F           0X46
  none,
// PS2_KEY_G           0X47
  note(F1),
// PS2_KEY_H           0X48
  note(G1),
// PS2_KEY_I           0X49
  note(c3),
// PS2_KEY_J           0X4A
  note(A1),
// PS2_KEY_K           0X4B
  none,
// PS2_KEY_L           0X4C
  note(C2),
// PS2_KEY_M           0X4D
  note(b1),
// PS2_KEY_N           0X4E
  note(a1),
// PS2_KEY_O           0X4F
  note(d3),
// PS2_KEY_P           0X50
  note(e3),
// PS2_KEY_Q           0X51
  note(c2),
// PS2_KEY_R           0X52
  note(f2),
// PS2_KEY_S           0X53
  note(C1),
// PS2_KEY_T           0X54
  note(g2),
// PS2_KEY_U           0X55
  note(b2),
// PS2_KEY_V           0X56
  note(f1),
// PS2_KEY_W           0X57
  note(d2),
// PS2_KEY_X           0X58
  note(d1),
// PS2_KEY_Y           0X59
  note(a2),
// PS2_KEY_Z           0X5A
  note(c1),
// PS2_KEY_SEMI        0X5B
  none,
// PS2_KEY_BACK        0X5C
  none,
// PS2_KEY_OPEN_SQ     0X5D
  note(f3),
// PS2_KEY_CLOSE_SQ    0X5E
  note(g3),
// PS2_KEY_EQUAL       0X5F
  note(F3),
/* Some Numeric keypads have a comma key */
// PS2_KEY_KP_COMMA    0x60
  none,
// PS2_KEY_F1          0X61
  none,
// PS2_KEY_F2          0X62
  none,
// PS2_KEY_F3          0X63
  none,
// PS2_KEY_F4          0X64
  none,
// PS2_KEY_F5          0X65
  none,
// PS2_KEY_F6          0X66
  none,
// PS2_KEY_F7          0X67
  none,
// PS2_KEY_F8          0X68
  none,
// PS2_KEY_F9          0X69
  none,
// PS2_KEY_F10         0X6A
  none,
// PS2_KEY_F11         0X6B
  none,
// PS2_KEY_F12         0X6C
  none,
// PS2_KEY_F13         0X6D
  none,
// PS2_KEY_F14         0X6E
  none,
// PS2_KEY_F15         0X6F
  none,
// PS2_KEY_F16         0X70
  none,
// PS2_KEY_F17         0X71
  none,
// PS2_KEY_F18         0X72
  none,
// PS2_KEY_F19         0X73
  none,
// PS2_KEY_F20         0X74
  none,
// PS2_KEY_F21         0X75
  none,
// PS2_KEY_F22         0X76
  none,
// PS2_KEY_F23         0X77
  none,
// PS2_KEY_F24         0X78
  none,
// PS2_KEY_NEXT_TR     0X79
  none,
// PS2_KEY_PREV_TR     0X7A
  none,
// PS2_KEY_STOP        0X7B
  none,
// PS2_KEY_PLAY        0X7C
  none,
// PS2_KEY_MUTE        0X7D
  none,
// PS2_KEY_VOL_UP      0X7E
  none,
// PS2_KEY_VOL_DN      0X7F
  none,
// PS2_KEY_MEDIA       0X80
  none,
// PS2_KEY_EMAIL       0X81
  none,
// PS2_KEY_CALC        0X82
  none,
// PS2_KEY_COMPUTER    0X83
  none,
// PS2_KEY_WEB_SEARCH  0X84
  none,
// PS2_KEY_WEB_HOME    0X85
  none,
// PS2_KEY_WEB_BACK    0X86
  none,
// PS2_KEY_WEB_FORWARD 0X87
  none,
// PS2_KEY_WEB_STOP    0X88
  none,
// PS2_KEY_WEB_REFRESH 0X89
  none,
// PS2_KEY_WEB_FAVOR   0X8A
  none,
// PS2_KEY_EUROPE2     0X8B
  none,
// PS2_KEY_POWER       0X8C
  none,
// PS2_KEY_SLEEP       0X8D
  none,
// PS2_KEY_WAKE        0X90
  none,
// PS2_KEY_INTL1       0X91
  none,
// PS2_KEY_INTL2       0X92
  none,
// PS2_KEY_INTL3       0X93
  none,
// PS2_KEY_INTL4       0X94
  none,
// PS2_KEY_INTL5       0X95
  none,
// PS2_KEY_LANG1       0X96
  none,
// PS2_KEY_LANG2       0X97
  none,
// PS2_KEY_LANG3       0X98
  none,
// PS2_KEY_LANG4       0X99
  none,
// PS2_KEY_LANG5       0xA0
  none
};
